(function($){"use strict";var scrollticker;var rtl=$('body').hasClass('rtl');var simple=$('body').hasClass('style-simple');var top_bar_top='61px';var header_H=0;var pretty=false;var mobile_init_W=1240;jQuery('.helper .link.toggle').click(function(e){e.preventDefault();var el=jQuery(this);var id=el.attr('data-rel');var parent=el.closest('.helper');if(el.hasClass('active')){el.removeClass('active');parent.find('.helper_content > .item-'+id).removeClass('active').slideUp(200);}else{parent.find('.links > .link.active').removeClass('active');parent.find('.helper_content > .item.active').slideUp(200)
el.addClass('active');parent.find('.helper_content > .item-'+id).addClass('active').slideDown(200);}
setTimeout(function(){mfn_sidebar();},200);});"use strict";jQuery(window).bind("debouncedresize",function(){iframesHeight();jQuery('.masonry.isotope').isotope();jQuery('.masonry.gallery').isotope('layout');zoomBoxVerticalAlign();});function zoomBoxVerticalAlign(){jQuery('body:not(.style-simple) .zoom_box').each(function(){var el=jQuery(this);var elH=el.height();var desc=el.find('.desc_wrap');var descH=desc.height();var padding=(elH-descH)/2;desc.css('padding-top',padding+'px');});}
zoomBoxVerticalAlign();function iframeHeight(item,ratio){var itemW=item.width();var itemH=itemW*ratio;if(itemH<147)itemH=147;item.height(itemH);}
function iframesHeight(){iframeHeight(jQuery(".blog_wrapper .post-photo-wrapper .mfn-jplayer, .blog_wrapper .post-photo-wrapper iframe, .post-related .mfn-jplayer, .post-related iframe, .blog_slider_ul .mfn-jplayer, .blog_slider_ul iframe"),0.78);iframeHeight(jQuery(".single-post .single-photo-wrapper .mfn-jplayer, .single-post .single-photo-wrapper iframe"),0.4);iframeHeight(jQuery(".section-portfolio-header .mfn-jplayer, .section-portfolio-header iframe"),0.4);}
iframesHeight();var topBarTop='61px';var mfn_header_height=0;function mfn_stickyH(){if(jQuery('body').hasClass('header-below')){mfn_header_height=jQuery('.mfn-main-slider').innerHeight()+jQuery('#Header').innerHeight();}else{mfn_header_height=jQuery('#Top_bar').innerHeight()+jQuery('#Action_bar').innerHeight();}}
function mfn_sticky(){if(jQuery('body').hasClass('sticky-header')){var start_y=mfn_header_height;var window_y=jQuery(window).scrollTop();if(window_y>start_y){if(!(jQuery('#Top_bar').hasClass('is-sticky'))){jQuery('.header-classic .header_placeholder').css('height',jQuery('#Top_bar').innerHeight()-jQuery('#Action_bar').innerHeight());jQuery('.header-stack   .header_placeholder').css('height',71);jQuery('.header-below   .header_placeholder').css('height',jQuery('#Top_bar').innerHeight());jQuery('.minimalist-header .header_placeholder').css('height',jQuery('#Top_bar').innerHeight());jQuery('#Top_bar').addClass('is-sticky').css('top',-60).animate({'top':jQuery('#wpadminbar').innerHeight()},300);}}else{if(jQuery('#Top_bar').hasClass('is-sticky')){jQuery('.header_placeholder').css('height',0);jQuery('#Top_bar').removeClass('is-sticky').css('top',topBarTop);}}}}
function mfn_sidebar(){if(jQuery('.with_aside .four.columns').length){var maxH=jQuery('#Content .sections_group').height()-20
jQuery('.with_aside .four.columns .widget-area').each(function(){jQuery(this).css('min-height',0);if(jQuery(this).height()>maxH){maxH=jQuery(this).height();}});jQuery('.with_aside .four.columns .widget-area').css('min-height',maxH+'px');}}
function mfn_equalH_wrap(){jQuery('.section.equal-height-wrap .section_wrapper').each(function(){var maxH=0;jQuery('> .wrap',jQuery(this)).each(function(){jQuery(this).css('height','auto');if(jQuery(this).innerHeight()>maxH){maxH=jQuery(this).innerHeight();}});jQuery('> .wrap',jQuery(this)).css('height',maxH+'px');});}
function mfn_equalH(){jQuery('.section.equal-height .mcb-wrap-inner').each(function(){var maxH=0;jQuery('> .column',jQuery(this)).each(function(){jQuery(this).css('height','auto');if(jQuery(this).height()>maxH){maxH=jQuery(this).height();}});jQuery('> .column',jQuery(this)).css('height',maxH+'px');});}
jQuery('.overlay-menu-toggle').click(function(e){e.preventDefault();jQuery(this).toggleClass('focus');jQuery('#Overlay').stop(true,true).fadeToggle(500);var menuH=jQuery('#Overlay nav').height()/2;jQuery('#Overlay nav').css('margin-top','-'+menuH+'px');});function mfn_footer(){if(jQuery('.footer-fixed #Footer, .footer-sliding #Footer').length){var footerH=jQuery('#Footer').height();jQuery('#Content').css('margin-bottom',footerH+'px');}}
function mfn_header(){var rightW=jQuery('.top_bar_right').innerWidth();var parentW=jQuery('#Top_bar .one').innerWidth()-10;var leftW=parentW-rightW;jQuery('.top_bar_left, .menu > li > ul.mfn-megamenu ').width(leftW);}
function mfn_sectionH(){var windowH=jQuery(window).height();var offset=0;if($('.section.full-screen:not(.hide-desktop)').length>1){offset=5;}
$('.section.full-screen').each(function(){var section=$(this);var wrapper=$('.section_wrapper',section);section.css('padding',0).css('min-height',windowH+offset);var padding=(windowH+offset-wrapper.height())/2;if(padding<50)padding=50;wrapper.css('padding-top',padding+10).css('padding-bottom',padding-10);});}
function adminBarH(){var height=0;if($('body').hasClass('admin-bar')){height+=$('#wpadminbar').innerHeight();}
if($('body').hasClass('woocommerce-demo-store')){height+=$('body > p.demo_store').innerHeight();}
return height;}
function mfn_introH(){var windowH=$(window).height()-$('#Header_wrapper').height()-adminBarH();$('#Intro.full-screen').each(function(){var el=$(this);var inner=$('.intro-inner',el);el.css('padding',0).css('min-height',windowH);var padding=(windowH-inner.height())/2;inner.css('padding-top',padding).css('padding-bottom',padding);});}
function hashNav(){var hash=window.location.hash;if(hash&&jQuery(hash).length){var stickyH=jQuery('.sticky-header #Top_bar').innerHeight();var tabsHeaderH=jQuery(hash).siblings('.ui-tabs-nav').innerHeight();jQuery('html, body').animate({scrollTop:jQuery(hash).offset().top-stickyH-tabsHeaderH},500);}}
function onePageActive(){if($('body').hasClass('one-page')){var stickyH=$('.sticky-header #Top_bar').innerHeight();var windowT=$(window).scrollTop();var start=windowT+stickyH+$('#wpadminbar').innerHeight()+1;var first=false;$('div[data-id]').each(function(){if($(this).visible(true)){if(!first){first=$(this);}else if(($(this).offset().top<start)&&($(this).offset().top>first.offset().top)){first=$(this);}}
if(first){var newActive=first.attr('data-id');var active='[data-hash="'+newActive+'"]';if(newActive){var menu=$('#menu');menu.find('li').removeClass('current-menu-item current-menu-parent current-menu-ancestor current_page_item current_page_parent current_page_ancestor');$(active,menu).closest('li').addClass('current-menu-item').closest('.menu > li').addClass('current-menu-item');}}});}}
function niceScrollFix(){var el=jQuery('body > .nicescroll-rails');if(el.length){if(el.is(":visible")){jQuery('body').addClass('nice-scroll');}else{jQuery('body').removeClass('nice-scroll');}}}
jQuery(window).load(function(){mfn_equalH_wrap();mfn_equalH();});jQuery(document).ready(function(){topBarTop=parseInt(jQuery('#Top_bar').css('top'),10);if(topBarTop<0)topBarTop=61;topBarTop=topBarTop+'px';jQuery('.before_after.twentytwenty-container').twentytwenty();mfnSliderContent();mfnSliderOffer();mfnSliderOfferThumb();mfnSliderBlog();mfnSliderClients();mfnSliderPortfolio();mfnSliderShop();mfnSliderTestimonials();jQuery('.responsive-menu-toggle').click(function(e){e.preventDefault();var el=jQuery(this)
var menu=jQuery('#Top_bar #menu');var menuWrap=menu.closest('.menu_wrapper');el.toggleClass('active');if(el.hasClass('is-sticky')&&el.hasClass('active')){var top=0;if(menuWrap.length)top=menuWrap.offset().top;jQuery('body,html').animate({scrollTop:top},200);}
menu.stop(true,true).slideToggle(200);});function sideSlide(){var slide=$('#Side_slide');var overlay=$('#body_overlay');var ss_mobile_init_W=mobile_init_W;var pos='right';var constructor=function(){if(!slide.hasClass('enabled')){$('nav#menu').detach().appendTo('#Side_slide .menu_wrapper');slide.addClass('enabled');}};var destructor=function(){if(slide.hasClass('enabled')){close();$('nav#menu').detach().prependTo('#Top_bar .menu_wrapper');slide.removeClass('enabled');}};var reload=function(){if(($(window).width()<ss_mobile_init_W)){constructor();}else{destructor();}};var init=function(){if(slide.hasClass('left')){pos='left';}
if($('body').hasClass('header-simple')){ss_mobile_init_W=9999;}
reload();};var reset=function(time){$('.lang-active.active',slide).removeClass('active').children('i').attr('class','icon-down-open-mini');$('.lang-wrapper',slide).fadeOut(0);$('.icon.search.active',slide).removeClass('active');$('.search-wrapper',slide).fadeOut(0);$('.menu_wrapper, .social',slide).fadeIn(time);};var button=function(){if(pos=='left'){slide.animate({'left':0},300);$('body').animate({'right':-125},300);}else{slide.animate({'right':0},300);$('body').animate({'left':-125},300);}
overlay.fadeIn(300);reset(0);};var close=function(){if(pos=='left'){slide.animate({'left':-250},300);$('body').animate({'right':0},300);}else{slide.animate({'right':-250},300);$('body').animate({'left':0},300);}
overlay.fadeOut(300);};$('.icon.search',slide).on('click',function(e){e.preventDefault();var el=$(this);if(el.hasClass('active')){$('.search-wrapper',slide).fadeOut(0);$('.menu_wrapper, .social',slide).fadeIn(300);}else{$('.search-wrapper',slide).fadeIn(300);$('.menu_wrapper, .social',slide).fadeOut(0);$('.lang-active.active',slide).removeClass('active').children('i').attr('class','icon-down-open-mini');$('.lang-wrapper',slide).fadeOut(0);}
el.toggleClass('active');});$('a.submit',slide).on('click',function(e){e.preventDefault();$('#side-form').submit();});$('.lang-active',slide).on('click',function(e){e.preventDefault();var el=$(this);if(el.hasClass('active')){$('.lang-wrapper',slide).fadeOut(0);$('.menu_wrapper, .social',slide).fadeIn(300);el.children('i').attr('class','icon-down-open-mini');}else{$('.lang-wrapper',slide).fadeIn(300);$('.menu_wrapper, .social',slide).fadeOut(0);el.children('i').attr('class','icon-up-open-mini');$('.icon.search.active',slide).removeClass('active');$('.search-wrapper',slide).fadeOut(0);}
el.toggleClass('active');});init();$('.responsive-menu-toggle').off('click');$('.responsive-menu-toggle').on('click',function(e){e.preventDefault();button();});overlay.on('click',function(e){close();});$('.close',slide).on('click',function(e){e.preventDefault();close();});$(slide).on('click',function(e){if($(e.target).is(slide)){reset(300);}});$(window).on('debouncedresize',reload);}
if($('body').hasClass('mobile-side-slide')){sideSlide();}
function mainMenu(){var mm_mobile_init_W=mobile_init_W;if($('body').hasClass('header-simple')||$('#Header_creative.dropdown').length){mm_mobile_init_W=9999;}
$('#menu > ul.menu').mfnMenu({addLast:true,arrows:true,mobileInit:mm_mobile_init_W,});$('#secondary-menu > ul.secondary-menu').mfnMenu({mobileInit:mm_mobile_init_W,});}
mainMenu();mfn_stickyH()
mfn_sticky();function onePageScroll(){if(!jQuery('body').hasClass('one-page')){var menu=jQuery('#menu');if(menu.find('li.scroll').length>1){menu.find('li.current-menu-item:not(:first)').removeClass('current-menu-item currenet-menu-parent current-menu-ancestor current_page_item current_page_parent current_page_ancestor');menu.find('a').click(function(){jQuery(this).closest('li').siblings('li').removeClass('current-menu-item currenet-menu-parent current-menu-ancestor current_page_item current_page_parent current_page_ancestor');jQuery(this).closest('li').addClass('current-menu-item');});}}}
onePageScroll();function onePageMenu(){if($('body').hasClass('one-page')){var menu=$('#menu');$('a[href]',menu).each(function(){var url=$(this).attr('href');if(url&&url.split('#')[1]){var hash='#'+url.split('#')[1];if(hash&&$(hash).length){$(this).attr('data-hash',hash);$(hash).attr('data-id',hash);}
var vcHash='#'+url.split('#')[1];var vcClass='.vc_row.'+url.split('#')[1];if(vcClass&&$(vcClass).length){$(this).attr('data-hash',vcHash);$(vcClass).attr('data-id',vcHash);}}});var hash;var activeSelector='.menu > li.current-menu-item, .menu > li.current-menu-parent, .menu > li.current-menu-ancestor, .menu > li.current-page-ancestor, .menu > li.current_page_item, .menu > li.current_page_parent, .menu > li.current_page_ancestor';if($(activeSelector,menu).length){$(activeSelector,menu).not(':first').removeClass('current-menu-item current-menu-parent current-menu-ancestor current-page-ancestor current_page_item current_page_parent current_page_ancestor');hash=$(activeSelector,menu).find('a[data-hash]').attr('data-hash');if(hash){hash='[data-id="'+hash+'"]';if($(hash).length&&$(hash).visible(true)){}else{$(activeSelector,menu).removeClass('current-menu-item current-menu-parent current-menu-ancestor current-page-ancestor current_page_item current_page_parent current_page_ancestor').closest('.menu > li').removeClass('current-menu-item current-menu-parent current-menu-ancestor current-page-ancestor current_page_item current_page_parent current_page_ancestor');}}else{}}else{var first=$('.menu > li:first-child',menu);var firstA=first.children('a');if(firstA.attr('data-hash')){hash=firstA.attr('data-hash');hash='[data-id="'+hash+'"]';var wpadminbarH=$('#wpadminbar').innerHeight()*1;if($(hash).length&&($(hash).offset().top==wpadminbarH)){first.addClass('current-menu-item');}}}
$('#menu a[data-hash]').click(function(e){e.preventDefault();menu.find('li').removeClass('current-menu-item');$(this).closest('li').addClass('current-menu-item').closest('.menu > li').addClass('current-menu-item');var hash=$(this).attr('data-hash');hash='[data-id="'+hash+'"]';if($(window).width()<768){$('.responsive-menu-toggle').removeClass('active');$('#Top_bar #menu').hide();}
var headerFixedAbH=$('.header-fixed.ab-show #Action_bar').innerHeight();var tabsHeaderH=$(hash).siblings('.ui-tabs-nav').innerHeight();var offset=headerFixedAbH-tabsHeaderH-$('#wpadminbar').innerHeight();var stickyH=fixStickyHeaderH();if($('body').hasClass('header-below')&&$('#Content').length){if($(hash).offset().top<($('#Content').offset().top+60)){stickyH=-1;}}
$('html, body').animate({scrollTop:$(hash).offset().top-offset-stickyH},500);});}}
onePageMenu();function fixStickyHeaderH(){var stickyH=0;var topBar=$('.sticky-header #Top_bar');if(topBar.hasClass('is-sticky')){stickyH=$('.sticky-header #Top_bar').innerHeight();}else{topBar.addClass('is-sticky');stickyH=$('.sticky-header #Top_bar').innerHeight();topBar.removeClass('is-sticky');}
var responsive=$('.responsive-menu-toggle');if(responsive.length){if(responsive.is(":visible")){stickyH=0;}}
return stickyH;}
var cHeader='body:not(.header-open) #Header_creative';var cHeaderEl=jQuery(cHeader);var cHeaderCurrnet;function creativeHeader(){jQuery('.creative-menu-toggle').click(function(e){e.preventDefault();cHeaderEl.addClass('active')
if(jQuery('body').hasClass('header-rtl')){cHeaderEl.animate({'right':-1},500);}else{cHeaderEl.animate({'left':-1},500);}
cHeaderEl.find('.creative-wrapper').fadeIn(500);cHeaderEl.find('.creative-menu-toggle, .creative-social').fadeOut(500);});}
creativeHeader();jQuery(document).on('mouseenter',cHeader,function(){cHeaderCurrnet=1;})
jQuery(document).on('mouseleave',cHeader,function(){cHeaderCurrnet=null;setTimeout(function(){if(!cHeaderCurrnet){cHeaderEl.removeClass('active');if(jQuery('body').hasClass('header-rtl')){cHeaderEl.animate({'right':-200},500);}else{cHeaderEl.animate({'left':-200},500);}
cHeaderEl.find('.creative-wrapper').fadeOut(500);cHeaderEl.find('.creative-menu-toggle, .creative-social').fadeIn(500);}},1000);});jQuery('.downcount').each(function(){var el=jQuery(this);el.downCount({date:el.attr('data-date'),offset:el.attr('data-offset')});});jQuery('.tooltip-img').hover(function(){jQuery(this).find('.tooltip-content').stop(true,true).show();},function(){jQuery(this).find('.tooltip-content').stop(true,true).hide();});jQuery("#popup_contact > a.button").click(function(e){e.preventDefault();jQuery(this).parent().toggleClass('focus');});if(jQuery('body').hasClass('nice-scroll-on')&&jQuery(window).width()>767&&!navigator.userAgent.match(/(Android|iPod|iPhone|iPad|IEMobile|Opera Mini)/)){jQuery('html').niceScroll({autohidemode:false,cursorborder:0,cursorborderradius:5,cursorcolor:'#222222',cursorwidth:10,horizrailenabled:false,mousescrollstep:(window.mfn_nicescroll)?window.mfn_nicescroll:40,scrollspeed:60});jQuery('body').removeClass('nice-scroll-on').addClass('nice-scroll');niceScrollFix();}
jQuery('.gallery-icon > a').wrap('<div class="image_frame scale-with-grid"><div class="image_wrapper"></div></div>').prepend('<div class="mask"></div>').attr('rel','prettyphoto[gallery]').attr('data-rel','prettyphoto[gallery]').children('img').css('height','auto').css('width','100%');if((typeof(window.mfn_prettyphoto)!=='undefined'&&!window.mfn_prettyphoto.disable)){jQuery('a[rel^="prettyphoto"],a.woocommerce-main-image.zoom, .prettyphoto, a[data-rel^="prettyPhoto[product-gallery]"]').prettyPhoto({default_width:window.mfn_prettyphoto.width?window.mfn_prettyphoto.width:500,default_height:window.mfn_prettyphoto.height?window.mfn_prettyphoto.height:344,show_title:false,deeplinking:false,social_tools:false});}
jQuery('#Intro .intro-next').click(function(){var intro=jQuery(this).closest('#Intro');if(intro.next().length){jQuery('html, body').animate({scrollTop:intro.next().offset().top-fixStickyHeaderH()-jQuery('#wpadminbar').innerHeight()},500);}});jQuery('.greyscale .image_wrapper > a, .greyscale .client_wrapper .gs-wrapper, .greyscale.portfolio-photo a').has('img').BlackAndWhite({hoverEffect:true,intensity:1});jQuery(".sliding-top-control").click(function(e){e.preventDefault();jQuery('#Sliding-top .widgets_wrapper').slideToggle();jQuery('#Sliding-top').toggleClass('active');});jQuery("#search_button, #Top_bar .icon_close").click(function(e){e.preventDefault();jQuery('#Top_bar .search_wrapper').fadeToggle();});jQuery('.alert .close').click(function(e){e.preventDefault();jQuery(this).closest('.alert').hide(300);});jQuery('a.button_js').each(function(){var btn=jQuery(this);if(btn.find('.button_icon').length&&btn.find('.button_label').length){btn.addClass('kill_the_icon');}});jQuery('.fixed-nav').appendTo('body');jQuery('.feature_list ul li:nth-child(4n):not(:last-child)').after('<hr>');function checkIE(){var ua=window.navigator.userAgent;var msie=ua.indexOf("MSIE ");if(msie>0&&parseInt(ua.substring(msie+5,ua.indexOf(".",msie)))==9){jQuery("body").addClass("ie");}}
checkIE();var ua=navigator.userAgent,isMobileWebkit=/WebKit/.test(ua)&&/Mobile/.test(ua);if(!isMobileWebkit&&jQuery(window).width()>=768){$.stellar({horizontalScrolling:false,responsive:true});}
jQuery('.pager_load_more').click(function(e){e.preventDefault();var el=jQuery(this);var pager=el.closest('.pager_lm');var href=el.attr('href');var index=jQuery('.lm_wrapper').index(el.closest('.isotope_wrapper').find('.lm_wrapper'));el.fadeOut(50);pager.addClass('loading');$.get(href,function(data){var content=jQuery('.lm_wrapper:eq('+index+')',data).wrapInner('').html();if(jQuery('.lm_wrapper:eq('+index+')').hasClass('isotope')){jQuery('.lm_wrapper:eq('+index+')').append(jQuery(content)).isotope('reloadItems').isotope({sortBy:'original-order'});}else{jQuery(content).hide().appendTo('.lm_wrapper:eq('+index+')').fadeIn(1000);}
href=jQuery('.pager_load_more:eq('+index+')',data).attr('href');pager.removeClass('loading');if(href){el.fadeIn();el.attr('href',href);}
mfn_jPlayer();iframesHeight();mfn_sidebar();jQuery('.lm_wrapper.isotope').imagesLoaded().progress(function(){jQuery('.lm_wrapper.isotope').isotope('layout');});});});jQuery('.filters_buttons .open').click(function(e){e.preventDefault();var type=jQuery(this).closest('li').attr('class');jQuery('.filters_wrapper').show(200);jQuery('.filters_wrapper ul.'+type).show(200);jQuery('.filters_wrapper ul:not(.'+type+')').hide();});jQuery('.filters_wrapper .close a').click(function(e){e.preventDefault();jQuery('.filters_wrapper').hide(200);});jQuery('.portfolio_next_js').click(function(e){e.preventDefault();var stickyH=jQuery('#Top_bar.is-sticky').innerHeight();var item=jQuery(this).closest('.portfolio-item').next();if(item.length){jQuery('html, body').animate({scrollTop:item.offset().top-stickyH},500);}});jQuery('.portfolio_prev_js').click(function(e){e.preventDefault();var stickyH=jQuery('#Top_bar.is-sticky').innerHeight();var item=jQuery(this).closest('.portfolio-item').prev();if(item.length){jQuery('html, body').animate({scrollTop:item.offset().top-stickyH},500);}});if(typeof(tabs)!=='undefined'){jQuery(".jq-tabs").tabs();}
jQuery('li.scroll > a, a.scroll').click(function(){var url=jQuery(this).attr('href');var hash='#'+url.split('#')[1];var stickyH=jQuery('.sticky-header #Top_bar').innerHeight();var tabsHeaderH=jQuery(hash).siblings('.ui-tabs-nav').innerHeight();if(hash&&jQuery(hash).length){jQuery('html, body').animate({scrollTop:jQuery(hash).offset().top-stickyH-tabsHeaderH},500);}});jQuery('.mfn-acc').each(function(){var el=jQuery(this);if(el.hasClass('openAll')){el.find('.question').addClass("active").children(".answer").show();}else{var active_tab=el.attr('data-active-tab');if(el.hasClass('open1st'))active_tab=1;if(active_tab){el.find('.question').eq(active_tab-1).addClass("active").children(".answer").show();}}});jQuery(".mfn-acc .question > .title").click(function(){if(jQuery(this).parent().hasClass("active")){jQuery(this).parent().removeClass("active").children(".answer").slideToggle(200);}else{if(!jQuery(this).closest('.mfn-acc').hasClass('toggle')){jQuery(this).parents(".mfn-acc").children().each(function(){if(jQuery(this).hasClass("active")){jQuery(this).removeClass("active").children(".answer").slideToggle(200);}});}
jQuery(this).parent().addClass("active");jQuery(this).next(".answer").slideToggle(200);}});function mfn_jPlayer(){jQuery('.mfn-jplayer').each(function(){var m4v=jQuery(this).attr('data-m4v');var poster=jQuery(this).attr('data-img');var swfPath=jQuery(this).attr('data-swf');var cssSelectorAncestor='#'+jQuery(this).closest('.mfn-jcontainer').attr('id');jQuery(this).jPlayer({ready:function(){jQuery(this).jPlayer('setMedia',{m4v:m4v,poster:poster});},play:function(){jQuery(this).jPlayer('pauseOthers');},size:{cssClass:'jp-video-360p',width:'100%',height:'360px'},swfPath:swfPath,supplied:'m4v',cssSelectorAncestor:cssSelectorAncestor,wmode:'opaque'});});}
mfn_jPlayer();jQuery('#back_to_top').click(function(){jQuery('body,html').animate({scrollTop:0},500);return false;});jQuery('.section .section-nav').click(function(){var el=jQuery(this);var section=el.closest('.section');if(el.hasClass('prev')){if(section.prev().length){jQuery('html, body').animate({scrollTop:section.prev().offset().top},500);}}else{if(section.next().length){jQuery('html, body').animate({scrollTop:section.next().offset().top},500);}}});function addToCart(){jQuery('body').on('click','.add_to_cart_button',function(){jQuery(this).closest('.product').addClass('adding-to-cart').removeClass('added-to-cart');});jQuery('body').bind('added_to_cart',function(){jQuery('.adding-to-cart').removeClass('adding-to-cart').addClass('added-to-cart');});}
addToCart();function iframeHeight(item,ratio){var itemW=item.width();var itemH=itemW*ratio;if(itemH<147)itemH=147;item.height(itemH);}
function iframesHeight(){iframeHeight(jQuery(".blog_wrapper .post-photo-wrapper .mfn-jplayer, .blog_wrapper .post-photo-wrapper iframe, .post-related .mfn-jplayer, .post-related iframe, .blog_slider_ul .mfn-jplayer, .blog_slider_ul iframe"),0.78);iframeHeight(jQuery(".single-post .single-photo-wrapper .mfn-jplayer, .single-post .single-photo-wrapper iframe"),0.4);iframeHeight(jQuery(".section-portfolio-header .mfn-jplayer, .section-portfolio-header iframe"),0.4);}
iframesHeight();jQuery(window).bind("debouncedresize",function(){iframesHeight();jQuery('.masonry.isotope,.isotope').isotope();mfn_carouFredSel_height();mfn_sidebar();mfn_footer();mfn_header();mfn_sectionH();mfn_introH();niceScrollFix();});function isotopeFilter(domEl,isoWrapper){var filter=domEl.attr('data-rel');isoWrapper.isotope({filter:filter});}
jQuery('.isotope-filters .filters_wrapper').find('li:not(.close) a').click(function(e){e.preventDefault();var filters=jQuery(this).closest('.isotope-filters');var parent=filters.attr('data-parent');if(parent){parent=filters.closest('.'+parent);var isoWrapper=parent.find('.isotope').first()}else{var isoWrapper=jQuery('.isotope');}
filters.find('li').removeClass('current-cat');jQuery(this).closest('li').addClass('current-cat');isotopeFilter(jQuery(this),isoWrapper);});jQuery('.isotope-filters .filters_buttons').find('li.reset a').click(function(e){e.preventDefault();jQuery('.isotope-filters .filters_wrapper').find('li').removeClass('current-cat');isotopeFilter(jQuery(this),jQuery('.isotope'));});mfn_carouFredSel_height();mfn_sidebar();mfn_footer();mfn_header();mfn_sectionH();hashNav();});jQuery(window).scroll(function(){mfn_stickyH();mfn_sticky();onePageActive();});jQuery(window).load(function(){jQuery('.portfolio_wrapper  .isotope:not(.masonry-flat)').isotope({itemSelector:'.portfolio-item',layoutMode:'fitRows'});jQuery('.portfolio_wrapper .masonry-flat').isotope({itemSelector:'.portfolio-item',masonry:{columnWidth:1}});jQuery('.masonry.isotope').isotope({itemSelector:'.isotope-item',layoutMode:'masonry'});$('.isotope.masonry, .isotope.masonry-hover, .isotope.masonry-minimal').isotope({itemSelector:'.isotope-item',layoutMode:'masonry',});jQuery('.chart').waypoint({offset:'100%',triggerOnce:true,handler:function(){var color=jQuery(this).attr('data-color');jQuery(this).easyPieChart({animate:1000,barColor:color,lineCap:'circle',lineWidth:8,size:140,scaleColor:false,trackColor:'#f8f8f8'});}});jQuery('.bars_list').waypoint({offset:'100%',triggerOnce:true,handler:function(){jQuery(this).addClass('hover');}});jQuery('.progress_icons').waypoint({offset:'100%',triggerOnce:true,handler:function(){var el=jQuery(this);var active=el.attr('data-active');var color=el.attr('data-color');var icon=el.find('.progress_icon');var timeout=200;icon.each(function(i){if(i<active){var time=(i+1)*timeout;setTimeout(function(){jQuery(icon[i]).addClass('themebg').css('background-color',color);},time);}});}});jQuery('.animate-math .number').waypoint({offset:'100%',triggerOnce:true,handler:function(){var el=jQuery(this);var duration=Math.floor((Math.random()*1000)+1000);var to=el.attr('data-to');jQuery({property:0}).animate({property:to},{duration:duration,easing:'linear',step:function(){el.text(Math.floor(this.property));},complete:function(){el.text(this.property);}});}});mfn_carouFredSel_height();mfn_sidebar();mfn_footer();mfn_header();mfn_sectionH();hashNav();niceScrollFix();});jQuery(document).mouseup(function(e){if(jQuery("#searchform").has(e.target).length===0){if(jQuery("#searchform").hasClass('focus')){jQuery(this).find('.icon_close').click();}}});function mfn_carouFredSel_height(){jQuery('.caroufredsel_wrapper > ul').each(function(){var el=jQuery(this);var maxH=0;el.children('li').each(function(){if(jQuery(this).innerHeight()>maxH){maxH=jQuery(this).innerHeight();}});el.closest('.caroufredsel_wrapper').height(maxH);});}
function slickAutoResponsive(slider){var width=slider.width();var count=Math.ceil(width/380);if(count<1)count=1;if(count>5)count=5;return count;}
function mfnSliderContent(){var pager=function(el,i){return'<a>'+i+'</a>';};$('.content_slider_ul').each(function(){var slider=$(this);var count=1;var centerMode=false;if(slider.closest('.content_slider').hasClass('carousel')){count=slickAutoResponsive(slider);$(window).bind('debouncedresize',function(){slider.slick('slickSetOption','slidesToShow',slickAutoResponsive(slider),false);slider.slick('slickSetOption','slidesToScroll',slickAutoResponsive(slider),true);});}
if(slider.closest('.content_slider').hasClass('center')){centerMode=true;}
if(slider.siblings('.slider_prev').length){slider.slick({cssEase:'cubic-bezier(.4,0,.2,1)',dots:true,infinite:true,touchThreshold:10,speed:300,centerMode:centerMode,centerPadding:'20%',prevArrow:slider.siblings('.slider_prev'),nextArrow:slider.siblings('.slider_next'),adaptiveHeight:true,appendDots:slider.siblings('.slider_pager'),customPaging:pager,rtl:rtl?true:false,autoplay:window.mfn_sliders.slider?true:false,autoplaySpeed:window.mfn_sliders.slider?window.mfn_sliders.slider:5000,slidesToShow:count,slidesToScroll:count});}else{slider.slick({cssEase:'cubic-bezier(.4,0,.2,1)',dots:true,infinite:true,touchThreshold:10,speed:300,centerMode:centerMode,centerPadding:'20%',prevArrow:'<a class="button button_js slider_prev" href="#"><span class="button_icon"><i class="icon-left-open-big"></i></span></a>',nextArrow:'<a class="button button_js slider_next" href="#"><span class="button_icon"><i class="icon-right-open-big"></i></span></a>',adaptiveHeight:true,appendDots:slider.siblings('.slider_pager'),customPaging:pager,rtl:rtl?true:false,autoplay:window.mfn_sliders.slider?true:false,autoplaySpeed:window.mfn_sliders.slider?window.mfn_sliders.slider:5000,slidesToShow:count,slidesToScroll:count});}});}
function mfnSliderTestimonials(){var pager=function(el,i){var img=$(el.$slides[i]).find('.single-photo-img').html();return'<a>'+img+'</a>';};$('.testimonials_slider_ul').each(function(){var slider=$(this);slider.slick({cssEase:'ease-out',dots:true,infinite:true,touchThreshold:10,speed:300,prevArrow:'<a class="button button_js slider_prev" href="#"><span class="button_icon"><i class="icon-left-open-big"></i></span></a>',nextArrow:'<a class="button button_js slider_next" href="#"><span class="button_icon"><i class="icon-right-open-big"></i></span></a>',adaptiveHeight:true,appendDots:slider.siblings('.slider_pager'),customPaging:pager,autoplay:window.mfn_sliders.testimonials?true:false,autoplaySpeed:window.mfn_sliders.testimonials?window.mfn_sliders.testimonials:5000,slidesToShow:1,slidesToScroll:1});});}
function mfnSliderOffer(){jQuery('.offer_ul').each(function(){jQuery(this).carouFredSel({circular:true,responsive:true,items:{visible:1,width:100},scroll:{duration:500,easing:'swing',onAfter:function(){jQuery(this).closest('.offer').find('.current').text(jQuery(this).triggerHandler("currentPosition")+1);}},prev:{button:function(){return jQuery(this).closest('.offer').find('.slider_prev');}},next:{button:function(){return jQuery(this).closest('.offer').find('.slider_next');}},auto:{play:window.mfn_sliders.offer?true:false,timeoutDuration:window.mfn_sliders.offer?window.mfn_sliders.offer:2500,},swipe:{onTouch:true,onMouse:true,onBefore:function(){jQuery(this).find('a').addClass('disable');jQuery(this).find('li').trigger('mouseleave');},onAfter:function(){jQuery(this).find('a').removeClass('disable');jQuery(this).closest('.offer').find('.current').text(jQuery(this).triggerHandler("currentPosition")+1);}}});jQuery(this).on('click','a.disable',function(){return false;});var count=jQuery(this).children('.offer_li').length;jQuery(this).closest('.offer').find('.count').text(count);});}
function mfnSliderOfferThumb_Pager(nr){var thumb=jQuery(this).closest('.offer_thumb').find('.offer_thumb_li.id_'+nr+' .thumbnail img').attr('src');return'<a href="#'+nr+'"><img src="'+thumb+'" alt="'+nr+'" /></a>';}
function mfnSliderOfferThumb(){jQuery('.offer_thumb_ul').each(function(){jQuery(this).carouFredSel({circular:true,responsive:true,items:{visible:1,width:100},pagination:{container:jQuery(this).closest('.offer_thumb').find('.slider_pagination'),anchorBuilder:mfnSliderOfferThumb_Pager},scroll:{duration:500,easing:'swing',onAfter:function(){jQuery(this).closest('.offer_thumb').find('.current').text(jQuery(this).triggerHandler("currentPosition")+1);}},auto:{play:window.mfn_sliders.offer?true:false,timeoutDuration:window.mfn_sliders.offer?window.mfn_sliders.offer:2500,},swipe:{onTouch:true,onMouse:true,onBefore:function(){jQuery(this).find('a').addClass('disable');jQuery(this).find('li').trigger('mouseleave');},onAfter:function(){jQuery(this).find('a').removeClass('disable');jQuery(this).closest('.offer_thumb').find('.current').text(jQuery(this).triggerHandler("currentPosition")+1);}}});jQuery(this).on('click','a.disable',function(){return false;});});}
function mfnSliderBlog(){jQuery('.blog_slider_ul').each(function(){jQuery(this).carouFredSel({circular:true,responsive:true,items:{width:380,visible:{min:1,max:4}},scroll:{duration:500,easing:'swing'},prev:{button:function(){return jQuery(this).closest('.blog_slider').find('.slider_prev');}},next:{button:function(){return jQuery(this).closest('.blog_slider').find('.slider_next');}},pagination:{container:function(){return jQuery(this).closest('.blog_slider').find('.slider_pagination');}},auto:{play:window.mfn_sliders.blog?true:false,timeoutDuration:window.mfn_sliders.blog?window.mfn_sliders.blog:2500,},swipe:{onTouch:true,onMouse:true,onBefore:function(){jQuery(this).find('a').addClass('disable');jQuery(this).find('li').trigger('mouseleave');},onAfter:function(){jQuery(this).find('a').removeClass('disable');}}});jQuery(this).on('click','a.disable',function(){return false;});});}
function mfnSliderClients(){jQuery('.clients_slider_ul').each(function(){jQuery(this).carouFredSel({circular:true,responsive:true,items:{width:380,visible:{min:1,max:4}},scroll:{duration:500,easing:'swing'},prev:{button:function(){return jQuery(this).closest('.clients_slider').find('.slider_prev');}},next:{button:function(){return jQuery(this).closest('.clients_slider').find('.slider_next');}},pagination:{container:function(){return jQuery(this).closest('.clients_slider').find('.slider_pagination');}},auto:{play:window.mfn_sliders.clients?true:false,timeoutDuration:window.mfn_sliders.clients?window.mfn_sliders.clients:2500,},swipe:{onTouch:true,onMouse:true,onBefore:function(){jQuery(this).find('a').addClass('disable');jQuery(this).find('li').trigger('mouseleave');},onAfter:function(){jQuery(this).find('a').removeClass('disable');}}});jQuery(this).on('click','a.disable',function(){return false;});});}
function mfnSliderShop(){jQuery('.shop_slider_ul').each(function(){jQuery(this).carouFredSel({circular:true,responsive:true,items:{width:380,visible:{min:1,max:4}},scroll:{duration:500,easing:'swing'},prev:{button:function(){return jQuery(this).closest('.shop_slider').find('.slider_prev');}},next:{button:function(){return jQuery(this).closest('.shop_slider').find('.slider_next');}},pagination:{container:function(){return jQuery(this).closest('.shop_slider').find('.slider_pagination');}},auto:{play:window.mfn_sliders.shop?true:false,timeoutDuration:window.mfn_sliders.shop?window.mfn_sliders.shop:2500,},swipe:{onTouch:true,onMouse:true,onBefore:function(){jQuery(this).find('a').addClass('disable');jQuery(this).find('li').trigger('mouseleave');},onAfter:function(){jQuery(this).find('a').removeClass('disable');}}});jQuery(this).on('click','a.disable',function(){});});}
function mfnSliderPortfolio(){$('.portfolio_slider_ul').each(function(){var slider=$(this);slider.slick({cssEase:'ease-out',dots:false,infinite:true,touchThreshold:10,speed:300,prevArrow:'<a class="slider_nav slider_prev themebg" href="#"><i class="icon-left-open-big"></i></a>',nextArrow:'<a class="slider_nav slider_next themebg" href="#"><i class="icon-right-open-big"></i></a>',autoplay:window.mfn_sliders.portfolio?true:false,autoplaySpeed:window.mfn_sliders.portfolio?window.mfn_sliders.portfolio:5000,slidesToShow:slickAutoResponsive(slider),slidesToScroll:slickAutoResponsive(slider)});$(window).bind('debouncedresize',function(){slider.slick('slickSetOption','slidesToShow',slickAutoResponsive(slider),false);slider.slick('slickSetOption','slidesToScroll',slickAutoResponsive(slider),true);});slider.on('dragstart','.slick-slide a[rel="prettyphoto"]',function(event){if(pretty){$(this).addClass('unbind-pretty').unbind('click.prettyphoto');}});slider.on('afterChange',function(event,slick,currentSlide,nextSlide){if(pretty){$('a.unbind-pretty[rel="prettyphoto"]',slider).prettyPhoto(pretty).removeClass('unbind-pretty');}});});}
window.mfn_nicescroll=25;window.mfn_prettyphoto={disable:0,width:0,height:0};window.mfn_sliders={blog:0,clients:0,offer:10000,portfolio:0,shop:0,slider:6000,testimonials:7000};jQuery(document).ready(function($){jQuery('.masonry.isotope,.isotope').isotope();jQuery('#configurator .control').click(function(e){e.preventDefault();if(jQuery('#configurator').hasClass('active')){jQuery('#configurator').removeClass('active').animate({'right':-272},500);}else{jQuery('#configurator').addClass('active').animate({'right':-1},500);}});jQuery('#mfn-demo-panel .control').click(function(e){e.preventDefault();if(jQuery('#mfn-demo-panel').hasClass('active')){jQuery('#mfn-demo-panel').removeClass('active').animate({'right':-367},500);}else{jQuery('#mfn-demo-panel').addClass('active').animate({'right':-1},500);}});demosSliderH();jQuery(".demos-slider").niceScroll({autohidemode:false,cursorborder:0,cursorborderradius:5,cursorcolor:'#222222',cursorwidth:0,horizrailenabled:false,mousescrollstep:40,scrollspeed:60});if(typeof stellar!=='undefined'&&$.isFunction(stellar)){var ua=navigator.userAgent,isMobileWebkit=/WebKit/.test(ua)&&/Mobile/.test(ua);if(!isMobileWebkit&&jQuery(window).width()>=768){if(window.mfn_parallax=='stellar'){jQuery.stellar({horizontalScrolling:false,responsive:true});}else{jQuery(window).enllax();}}else{jQuery('.section[data-enllax-ratio], .section[data-stellar-ratio]').css('background-attachment','scroll');jQuery('div[data-enllax-ratio], div[data-stellar-ratio]').css('background-attachment','scroll');}}});})(jQuery);function demosSliderH(){var panel=jQuery('#mfn-demo-panel');var panelH=panel.height()-panel.find('.header').height();jQuery(".demos-slider").height(panelH);}
(function($){"use strict";$(function(){function switch_style(){var el=$('.demo-switch');if($('body').hasClass('style-simple')){$('a.simple',el).addClass('active');}else{$('a.default',el).addClass('active');}
$('a',el).on('click',function(e){e.preventDefault();var style=$(this).attr('data-style');$('body').removeClass('style-default style-simple').addClass('style-'+style);$('a',el).removeClass('active');$('a.'+style,el).addClass('active');});}
switch_style();var wc_checkout_coupons={init:function(){$(document.body).on('click','a.showcoupon',this.show_coupon_form);$(document.body).on('click','.woocommerce-remove-coupon',this.remove_coupon);$('form.checkout_coupon').hide().submit(this.submit);},show_coupon_form:function(){$('.checkout_coupon').slideToggle(400,function(){$('.checkout_coupon').find(':input:eq(0)').focus();});return false;},submit:function(){var $form=$(this);if($form.is('.processing')){return false;}
$form.addClass('processing').block({message:null,overlayCSS:{background:'#fff',opacity:0.6}});var data={security:wc_checkout_params.apply_coupon_nonce,coupon_code:$form.find('input[name="coupon_code"]').val()};$.ajax({type:'POST',url:wc_checkout_params.wc_ajax_url.toString().replace('%%endpoint%%','apply_coupon'),data:data,success:function(code){$('.woocommerce-error, .woocommerce-message').remove();$form.removeClass('processing').unblock();if(code){$form.before(code);$form.slideUp();$(document.body).trigger('update_checkout',{update_shipping_method:false});}},dataType:'html'});return false;},remove_coupon:function(e){e.preventDefault();var container=$(this).parents('.woocommerce-checkout-review-order'),coupon=$(this).data('coupon');container.addClass('processing').block({message:null,overlayCSS:{background:'#fff',opacity:0.6}});var data={security:wc_checkout_params.remove_coupon_nonce,coupon:coupon};$.ajax({type:'POST',url:wc_checkout_params.wc_ajax_url.toString().replace('%%endpoint%%','remove_coupon'),data:data,success:function(code){$('.woocommerce-error, .woocommerce-message').remove();container.removeClass('processing').unblock();if(code){$('form.woocommerce-checkout').before(code);$(document.body).trigger('update_checkout',{update_shipping_method:false});$('form.checkout_coupon').find('input[name="coupon_code"]').val('');}},error:function(jqXHR){if(wc_checkout_params.debug_mode){console.log(jqXHR.responseText);}},dataType:'html'});}};var wc_checkout_login_form={init:function(){$(document.body).on('click','a.showlogin',this.show_login_form);},show_login_form:function(){$('form.login, form.woocommerce-form--login').slideToggle();return false;}};wc_checkout_coupons.init();wc_checkout_login_form.init();});})(jQuery);
